export enum DatabaseErrorCode {
    UNIQUE_CONSTRAINT = "UNIQUE_CONSTRAINT",
    FOREIGN_KEY_VIOLATION = "FOREIGN_KEY_VIOLATION",
    CONSTRAINT_VIOLATION = "CONSTRAINT_VIOLATION", // missing NON optional fields
    RECORD_NOT_FOUND = "RECORD_NOT_FOUND",
    DB_CONNECTION_ERROR = "DB_CONNECTION_ERROR",
    UNKNOWN_DB_ERROR = "UNKNOWN_DB_ERROR",
}